### ISSUE TITLE
Está no sitio errado entao nao funciona

### ISSUE THREAD

**Issue by afonso-saaa** [RuiFernandesLusofona/RuiFernandesLusofona.github.io#2]
https://github.com/RuiFernandesLusofona/RuiFernandesLusofona.github.io/blob/092ee5627af7dd8306cf31f04894654a936e8cbf/lab3/quizz.html#L143

esta linha do postman/get devias ter logo debaixo do parametro quando abres o main, assim  como tens nao funciona, tanto na viagem como no quiz

**Comment by RuiFernandesLusofona** [comment]
Obrigado, arranjei o erro agora
